client:
  timeout: 5s

schedule:
  jobs:
    Reqbin:
      interval: 5s
      tests:
        json:
          request:
            url: https://reqbin.com/echo/get/json
          response:
            extract:
              success: success
          ok: status_code == 200 && success == "true"
        post:
          request:
            method: post
            url: https://reqbin.com/echo/post/json
            queryparams:
              test: "1"
            headers:
              Content-Type: application/json
            body: |-
              {
                "login": "login",
                "password": "password"
              }
          response:
            extract:
              success: success
              value: data.0.value
              status: data.status
          ok: status_code == 200 && (success == "true" || (value > 0 && status == "ok"))
      ok: post && json
      values:
        value: 123

alerters:
  Pushover:
    default: true
    alwayssend: true
    request:
      method: POST
      url: https://api.pushover.net/1/messages.json
      headers:
        Content-Type: application/json
      body: |-
        {
          "token": "{{.TOKEN}}",
          "user": "{{.USER_TOKEN}}",
          "title": "{{.job}} - {{.value}}",
          "message": "{{.state}}"
        }
